spring:
  application:
    name: Config-Prod
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  datasource:
    url: jdbc:mysql://localhost:3306/microservices_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
        hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  main:
    allow-bean-definition-overriding: true
